If `config_file` is changed, update the dune.config
Previously I would see:

$ mirage configure -f config_test.ml
File "dune.config", line 5, characters 8-14:
5 |   (name config)
            ^^^^^^
Error: Module "Config" doesn't exist.
run ['dune' 'exec' '--root' '/home/djs/djs55/mirage-skeleton/tutorial/noop'
     '--' './config.exe' 'configure' '-f' 'config_test.ml']: exited with 1
```
The `dune.config` file has:
```
;; auto-generated by 'mirage configure -- remove these comments to
;; preserve the file after a `mirage clean`

(executable
  (name config)
  (flags (:standard -warn-error -A))
  (modules config_test)
  (libraries mirage))
```

Signed-off-by: David Scott <dave@recoil.org>